# Calculator application configuration file.

WINDOW_HEIGHT = 380
WINDOW_WIDTH = 300
WINDOW_TITLE = "Calculator"
WINDOW_BACKGROUND_COLOR = "#5cbeff"
WINDOW_DEFAULT_FONT = ("Verdana", 12, "normal")

SCIENTIFIC_NOTATION = "e"
DISPLAY_INITIAL_VALUE = "0"
DISPLAY_ERROR = "Error"
DISPLAY_OPERATORS = "+–×÷"
PYTHON_OPERATORS = "+-*/"

OPERATOR_MAP = dict(zip(PYTHON_OPERATORS, DISPLAY_OPERATORS))
